version: "3.9"

services:
  rust-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rust-api
    ports:
      - "8080:8080"
    environment:
      RUST_LOG: info
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3